### ISSUE TITLE
missing files？

### ISSUE THREAD

**Issue by zhizhusheng** [MegEngine/FINet#1]
├── modelnet40_half1_rm_rotate.txt
├── modelnet40_half2_rm_rotate.txt
 
 Where can I get these two files？thanks

**Comment by hxwork** [comment]
Hi,

Sorry for the late reply. These two files contain the names of the training and test categories (ModelNet40 dataset). The axisymmetrical categories are removed from the original ModelNet40 dataset, and you can download these two files [here](https://github.com/MegEngine/OMNet/tree/main/dataset/data).
