### ISSUE TITLE
How to use the trained model？

### ISSUE THREAD

**Issue by abchears** [MegEngine/FINet#2]
Hi author, thank you very much for your excellent work. I would like to ask, if I now have two tensors of shape n1x3 and n2X3, how should I use the trained model?

**Comment by hxwork** [comment]
Hi,

Thanks for your interest. We have no plan to provide the inference code, but I think it is easy to evaluate our model. Based on the evaluate.py, you may convert the format of your inputs to that of our `data_batch` ([L39](https://github.com/MegEngine/FINet/blob/5c07e7c0cafad67461c574633e7bb77257af6a96/evaluate.py#L39)). Then, the transformation (represented by a quaternion and a translation) between the inputs can be obtained from `output_batch` ([L43](https://github.com/MegEngine/FINet/blob/5c07e7c0cafad67461c574633e7bb77257af6a96/evaluate.py#L43)).

Best regards,
Hao
